#!/bin/bash

# **** This script runs on upstream knative ci server and is stored in GCP secret manger service ****
# It sets up the host entires and fetchs & runs environment setup script

# Usage
# . /tmp/ci-script <CI job name>

# CI_JOB is used to setup and patch code based on job type
if [ -z ${1} ]
then
    echo "Missing positional{1} argument for CI_JOB...."
    exit 1
fi
export CI_JOB=${1}

# Public IP of bastion node in PowerVS
BASTION_IP="130.198.103.76"

# add host entires
#echo "${BASTION_IP} cluster.ppc64le registry.apps.a9367076.nip.io ppc64le" >> /etc/hosts

#copy env setup script
scp -i /opt/cluster/knative-ssh -o MACs=hmac-sha2-256 -o StrictHostKeyChecking=no -oLogLevel=ERROR -o UserKnownHostsFile=/dev/null root@130.198.103.76:/opt/knative-upstream-ci/setup-environment.sh /tmp
scp -i /opt/cluster/knative-ssh -o MACs=hmac-sha2-256 -o StrictHostKeyChecking=no -oLogLevel=ERROR -o UserKnownHostsFile=/dev/null root@130.198.103.76:/opt/knative-upstream-ci/k8s.sh /tmp

if [ ! -f /tmp/setup-environment.sh ]
then
    echo "Couldn't fetch file from remote machine...."
    exit 1
fi
echo ${2}
# #run env setup script
chmod +x /tmp/setup-environment.sh
. /tmp/setup-environment.sh ${2}